- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - unzip
      - net-tools
      - openvpn
      - iptables
      - iptables-persistent
      - hostapd
      - dnsmasq
      - wireless-tools
      - dhcpcd5
      - python3-pip
      - python3-setuptools
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - python3-kubernetes
      - python3-yaml
    state: present

- name: Verify Python Kubernetes library installation
  command: python3 -c "import kubernetes; print('Kubernetes library OK')"
  register: k8s_check
  changed_when: false
  failed_when: false

- name: Display Python library status
  debug:
    msg: "{{ k8s_check.stdout if k8s_check.rc == 0 else 'Warning: Kubernetes library not available' }}"

- name: Create a unified dhcpcd.conf for all interfaces
  copy:
    dest: /etc/dhcpcd.conf
    mode: '0644'
    content: |
      # Global settings
      persistent
      option rapid_commit
      option domain_name_servers, domain_name, domain_search, host_name
      require dhcp_server_identifier
      slaac private

      # Static IP configuration for eth0 (WAN)
      interface eth0
      static ip_address=192.168.1.1/24
      static routers=192.168.1.254
      static domain_name_servers=8.8.8.8 1.1.1.1

      # Static IP configuration for wlan0 (AP)
      interface wlan0
      static ip_address=10.0.0.1/24
      nohook wpa_supplicant
