- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    sysctl_set: yes
    reload: yes

- name: Set iptables rules
  copy:
    dest: /etc/iptables/rules.v4
    content: |
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -o tun0 -j MASQUERADE
      COMMIT

      *filter
      :INPUT ACCEPT [0:0]
      :FORWARD ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      
      # VPN Traffic forwarding
      -A FORWARD -i wlan0 -o tun0 -j ACCEPT
      -A FORWARD -i tun0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
      
      # K3s Security Rules - Allow only from VPN network (10.0.0.0/24)
      -A INPUT -s 10.0.0.0/24 -p tcp --dport 6443 -j ACCEPT
      -A INPUT -s 192.168.1.0/24 -p tcp --dport 6443 -j DROP
      -A INPUT -s 10.0.0.0/24 -p tcp --dport 10250 -j ACCEPT
      -A INPUT -s 192.168.1.0/24 -p tcp --dport 10250 -j DROP
      -A INPUT -s 10.0.0.0/24 -p tcp --dport 30000:32767 -j ACCEPT
      -A INPUT -s 192.168.1.0/24 -p tcp --dport 30000:32767 -j DROP
      
      # K3s Internal cluster communication
      -A INPUT -s 10.42.0.0/16 -p udp --dport 8472 -j ACCEPT
      -A INPUT -s 10.43.0.0/16 -j ACCEPT
      -A INPUT -s 10.0.0.0/24 -p udp --dport 8472 -j ACCEPT
      
      # SSH access (keep existing access)
      -A INPUT -p tcp --dport 22 -j ACCEPT
      
      COMMIT

- name: Reload iptables
  shell: iptables-restore < /etc/iptables/rules.v4
