---
# Docker installation simple pour Raspberry Pi

- name: Remove old Docker packages
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Configure Docker daemon for VPN and no K3s conflict
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        },
        "storage-driver": "overlay2",
        "exec-opts": ["native.cgroupdriver=systemd"],
        "live-restore": true,
        "default-address-pools": [
          {
            "base": "172.17.0.0/16",
            "size": 24
          }
        ],
        "bip": "172.17.0.1/24",
        "dns": ["8.8.8.8", "1.1.1.1"]
      }
    mode: '0644'
  notify: restart docker

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Verify Docker installation
  command: docker --version
  register: docker_version
  changed_when: false

- name: Display Docker version
  debug:
    msg: "✅ Docker installé: {{ docker_version.stdout }}"